version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://appuser:secretpassword@localhost:5432/appdb?schema=public
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - api
    environment:
      VITE_API_BASE_URL: http://localhost:3000
    ports:
      - "8080:80"

volumes:
  db_data:
